import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,act,current,score,standings,assertState} from '../dist/engine.mjs';
const die=id=>({type:'die',id});
function base(){const s=act(createGame(['Анна','Константин'],1234),{type:'begin'});s.party.forEach(x=>{x.face='warrior';x.zone='active';});s.dungeon=[];s.lair=[];return s;}
function give(s,kind){const i=s.pool.findIndex(x=>x.kind===kind),[item]=s.pool.splice(i,1);current(s).items.push(item);return item.id;}
test('Имена и очередь: ровно три приключения для каждого из четырёх игроков',()=>{let s=createGame(['А','Б','В','Г'],4);for(let i=0;i<12;i++){assert.equal(current(s).name,['А','Б','В','Г'][i%4]);assert.equal(current(s).completed,Math.floor(i/4));s=act(s,{type:'begin'});s=act(s,{type:'flee'});}assert.equal(s.phase,'finished');assert.deepEqual(s.players.map(p=>p.completed),[3,3,3,3]);assert.throws(()=>act(s,{type:'begin'}));});
test('Можно выбрать число приключений от 1 до 10, по умолчанию остаётся 3',()=>{assert.equal(createGame(['А'],1).adventures,3);assert.throws(()=>createGame(['А'],1,0));assert.throws(()=>createGame(['А'],1,11));let s=createGame(['А','Б'],1,2);for(let i=0;i<4;i++){s=act(s,{type:'begin'});s=act(s,{type:'flee'});}assert.equal(s.phase,'finished');assert.deepEqual(s.players.map(p=>p.completed),[2,2]);assertState(s);});
test('Поддерживается партия до шести игроков',()=>{const names=['А','Б','В','Г','Д','Е'];let s=createGame(names,7,1);for(let i=0;i<6;i++){assert.equal(current(s).name,names[i]);s=act(s,{type:'begin'});s=act(s,{type:'flee'});}assert.equal(s.phase,'finished');assert.deepEqual(s.players.map(p=>p.completed),[1,1,1,1,1,1]);assert.throws(()=>createGame([...names,'Ж'],7));});
test('Воин бьёт группу гоблинов, но только одного скелета; неверное действие атомарно',()=>{let s=base();s.dungeon=[{id:0,face:'goblin'},{id:1,face:'goblin'},{id:2,face:'skeleton'},{id:3,face:'skeleton'}];const snapshot=structuredClone(s);assert.throws(()=>act(s,{type:'attack',source:die(0),targets:[2,3]}));assert.deepEqual(s,snapshot);s=act(s,{type:'attack',source:die(0),targets:[0,1]});assert.equal(s.party[0].zone,'grave');assert.equal(s.dungeon.length,2);assert.throws(()=>act(s,{type:'advance'}));});
test('Зелье может немедленно вернуть только что потраченный свиток другой гранью',()=>{let s=base();s.phase='loot';s.party[0].face='scroll';s.dungeon=[{id:0,face:'potion'}];s=act(s,{type:'drink',source:die(0),targets:[0],faces:['champion']});assert.equal(s.party[0].zone,'active');assert.equal(s.party[0].face,'champion');assert.equal(s.dungeon.length,0);});
test('Свиток нельзя перебросить им самим, из логова кубики недоступны',()=>{let s=base();s.party[0].face='scroll';s.lair=[0];s.dungeon=[{id:1,face:'goblin'}];assert.throws(()=>act(s,{type:'reroll',source:die(0),party:[0],dungeon:[]}));assert.throws(()=>act(s,{type:'reroll',source:die(0),party:[],dungeon:[0]}));s=act(s,{type:'reroll',source:die(0),party:[1],dungeon:[1]});assert.equal(s.party[0].zone,'grave');assert.ok(s.lair.includes(0));assertState(s);});
test('Дракон требует три разных типа, допускает сокровище и даёт награду',()=>{let s=base();s.phase='dragon';s.lair=[0,1,2,3];s.party[1].face='cleric';const wand=give(s,'wand');assert.throws(()=>act(s,{type:'slay',sources:[die(0),die(2),die(1)]}));s=act(s,{type:'slay',sources:[die(0),die(1),{type:'item',id:wand}]});assert.equal(s.lair.length,0);assert.equal(current(s).xp,1);assert.equal(current(s).items.length,1);assert.equal(s.phase,'regroup');});
test('Кольцо не даёт награды, приманка переносит все кубики уровня',()=>{let s=base();s.dungeon=[{id:0,face:'goblin'},{id:1,face:'chest'},{id:2,face:'potion'}];let id=give(s,'bait');s=act(s,{type:'item',id});assert.equal(s.lair.length,3);assert.equal(s.dungeon.length,0);s=act(act(s,{type:'advance'}),{type:'advance'});assert.equal(s.phase,'dragon');id=give(s,'ring');s=act(s,{type:'item',id});assert.equal(s.phase,'regroup');assert.equal(current(s).xp,0);assert.equal(current(s).items.length,0);});
test('Портал работает при монстрах, бегство сохраняет уже полученный опыт',()=>{let s=base();s.level=6;s.dungeon=[{id:0,face:'skeleton'}];const id=give(s,'portal');s=act(s,{type:'item',id});assert.equal(s.players[0].xp,6);assert.equal(s.turn,1);s=act(s,{type:'begin'});current(s).xp=2;give(s,'scale');s=act(s,{type:'flee'});assert.equal(s.players[1].xp,2);assert.equal(s.players[1].items.length,1);});
test('Сундук без жетонов даёт опыт; сокровища возвращаются в общий пул',()=>{let s=base();current(s).items.push(...s.pool);s.pool=[];s.phase='loot';s.dungeon=[{id:0,face:'chest'}];s=act(s,{type:'open',source:die(0),targets:[0]});assert.equal(current(s).xp,1);assert.equal(s.pool.length,0);assertState(s);});
test('Вор открывает несколько сундуков и получает отдельную награду за каждый',()=>{let s=base();s.phase='loot';s.party[0].face='thief';s.dungeon=[{id:0,face:'chest'},{id:1,face:'chest'},{id:2,face:'chest'}];const before=s.pool.length;s=act(s,{type:'open',source:die(0),targets:[0,1,2]});assert.equal(current(s).items.length,3);assert.equal(s.pool.length,before-3);assert.equal(s.dungeon.length,0);assertState(s);});
test('Подсчёт порталов, пар чешуек и разрешение ничьей',()=>{let s=base();give(s,'portal');give(s,'scale');give(s,'scale');give(s,'scale');assert.equal(score(current(s)),7);s.players[1].xp=7;assert.equal(standings(s)[0].name,'Константин');});
test('На 10-м уровне спуск запрещён; логово уменьшает число новых кубиков',()=>{let s=base();s.phase='regroup';s.level=6;s.lair=[0,1];s=act(s,{type:'descend'});assert.equal(s.dungeon.length+s.lair.length,7);s.phase='regroup';s.dungeon=[];s.level=10;assert.throws(()=>act(s,{type:'descend'}));s=act(s,{type:'rest'});assert.equal(s.players[0].xp,10);});
test('Сто полных партий: сохранение числа кубиков и 36 жетонов',()=>{for(let seed=1;seed<=100;seed++){let s=createGame(['Игрок'],seed);while(s.phase!=='finished'){if(['ready','end'].includes(s.phase)){s=act(s,{type:'begin'});continue;}if(s.phase==='battle'){const monster=s.dungeon.find(d=>['goblin','skeleton','slime'].includes(d.face));if(!monster){s=act(s,{type:'advance'});continue;}const fighter=s.party.find(d=>d.zone==='active'&&d.face!=='scroll');s=act(s,fighter?{type:'attack',source:die(fighter.id),targets:[monster.id]}:{type:'flee'});continue;}if(s.phase==='loot'){const chest=s.dungeon.find(d=>d.face==='chest'),fighter=s.party.find(d=>d.zone==='active'&&d.face!=='scroll');s=act(s,chest&&fighter?{type:'open',source:die(fighter.id),targets:[chest.id]}:{type:'advance'});continue;}if(s.phase==='dragon'){s=act(s,{type:'flee'});continue;}s=act(s,s.level<5?{type:'descend'}:{type:'rest'});assertState(s);}assert.equal(s.players[0].completed,3);}});
